// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Technical.Interview.WebApi.Data;

#nullable disable

namespace Technical.Interview.WebApi.Data.Migrations
{
    [DbContext(typeof(InterviewContext))]
    [Migration("20240508235619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Technical.Interview.WebApi.Entities.MarcasAuto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SitioWeb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9181437-053c-4217-80c1-08ed563d0b40"),
                            Nombre = "Toyota",
                            PaisOrigen = "Japan",
                            SitioWeb = "https://www.toyota.com/"
                        },
                        new
                        {
                            Id = new Guid("79c7dbf3-9a28-4476-832a-ee7af263c43f"),
                            Nombre = "Ford",
                            PaisOrigen = "United States",
                            SitioWeb = "https://www.ford.com/"
                        },
                        new
                        {
                            Id = new Guid("87209a57-138b-4f7a-8a7d-4add1045296d"),
                            Nombre = "Volkswagen",
                            PaisOrigen = "Germany",
                            SitioWeb = "https://www.vw.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
